version: '3.9'

services:
  jobot:
    build:
      context: .
    working_dir: /agents
    volumes:
      - .:/agents  # Mount application code for development
    networks:
      - joBot-network
    ports:
      - "5002:5002"  # Expose Flask app on port 5002
    environment:
      - FLASK_APP=agents/Server/app.py
      - FLASK_ENV=production
    depends_on:
      - mongo
      - selenium  # Ensure Selenium starts before Flask

  selenium:
    image: selenium/standalone-firefox
    container_name: selenium-server
    networks:
      - joBot-network
    ports:
      - "4444:4444"  # Expose Selenium WebDriver
    shm_size: 2gb  # Increase shared memory for browser stability

  mongo:
    image: mongo:latest  # Use official MongoDB image
    networks:
      - joBot-network
    ports:
      - "27017:27017"  # Expose MongoDB on the default port
    volumes:
      - ./data:/data/db  # Persist MongoDB data locally

networks:
  joBot-network:
    driver: bridge